volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - data:/var/lib/redis