volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - data:/var/lib/postgresql

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - data:/var/lib/redis
